POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhbmtrYSIsImlkIjoiNjViZTEyOTIyYWIxNTMxMjJjNmRkYjY3IiwiaWF0IjoxNzA2OTU1NDI2fQ.JQbuItRsgHgzK85k4yyn4UymW2nJCBn-2JpPvyAjLN8

{
    "title": "aku ankan raha huoli",
    "author": "aku",
    "url": "https://akuankka.fi/",
    "likes": 412320,
    "userId": "65be12922ab153122c6ddb67"
}
