DELETE http://localhost:3001/api/blogs/65be12f12ab153122c6ddb6e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhbmtrYSIsImlkIjoiNjViZTEyOTIyYWIxNTMxMjJjNmRkYjY3IiwiaWF0IjoxNzA2OTU1NjQwfQ.SNWHZSnrJzZdXA2lCV9-mX33OAkpfk-Dlroejx0QMBQ